version: '3'
services:
  book_catalog:
    image: book-catalog:latest
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    environment:
      - PORT=30001
      - DATABASE_URL=postgresql://db_722task7p2_c9x5_user:6r8t97SiRivkNhXcGJbmuBSgsy6zvUMk@dpg-crqfdkaj1k6c738fke90-a.oregon-postgres.render.com/db_722task7p2_c9x5
 
  inventory_management:
    image: inventory-management:latest
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    environment:
      - PORT=7001
      - DATABASE_URL=postgresql://db_722task7p2_c9x5_user:6r8t97SiRivkNhXcGJbmuBSgsy6zvUMk@dpg-crqfdkaj1k6c738fke90-a.oregon-postgres.render.com/db_722task7p2_c9x5