apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: 722task7c2.azurecr.io/inventory-management:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 30001
        env:
        - name: PORT
          value: "30001"
        - name: DATABASE_URL
          value: "postgresql://db_722task7p2_c9x5_user:6r8t97SiRivkNhXcGJbmuBSgsy6zvUMk@dpg-crqfdkaj1k6c738fke90-a.oregon-postgres.render.com/db_722task7p2_c9x5"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 30001
---
